#' make_param_file_subset
#'
#' @author Jeroen Pullens
#' @param WD Working Directory
#' @param x values for the parameters
#'
#' @examples
#' \dontrun{
#' make_param_file_subset(WD,c(1:26))
#' }
#'
make_param_file_subset<-function(WD,x){
  file<-paste(WD,"input/param.txt",sep="")
  cat("[bog]",file=file,sep="\n")
  cat("CO2ref = 350",file=file,append=TRUE,sep="\n")
  cat("CritNClvms = 0.014",file=file,append=TRUE,sep="\n")
  cat("CritNCacro = 0.014",file=file,append=TRUE,sep="\n")
  cat("CritNCcato = 0.014",file=file,append=TRUE,sep="\n")
  cat("FixDepthtcnp = 250",file=file,append=TRUE,sep="\n")
  cat("FixDepthlcnp = 150",file=file,append=TRUE,sep="\n")
  cat("MinDepthlvms = 10",file=file,append=TRUE,sep="\n")
  cat("MaxDepthlvms = 50",file=file,append=TRUE,sep="\n")
  cat("MaxDepthacro = 150",file=file,append=TRUE,sep="\n")
  cat("MicrEfflvms = 0.2",file=file,append=TRUE,sep="\n")
  cat("MicrEffacro = 0.2",file=file,append=TRUE,sep="\n")
  cat("MicrEffcato = 0.2",file=file,append=TRUE,sep="\n")
  cat("Mutcnp = 0.99",file=file,append=TRUE,sep="\n")
  cat("Mulcnp = 0.98",file=file,append=TRUE,sep="\n")
  cat("Mulvms = 0.85",file=file,append=TRUE,sep="\n")
  cat("Muacro = 0.70",file=file,append=TRUE,sep="\n")
  cat("Mucato = 0.40",file=file,append=TRUE,sep="\n")
  cat("TimeStep = 1",file=file,append=TRUE,sep="\n")
  cat("TDecParlvms = 0.20",file=file,append=TRUE,sep="\n")
  cat("TDecParacro = 0.20",file=file,append=TRUE,sep="\n")
  cat("TDecParcato = 0.10",file=file,append=TRUE,sep="\n")
  cat("TOptDec = 37",file=file,append=TRUE,sep="\n")

  cat("",file=file,sep="\n",append=TRUE)

  cat("[gram]",file=file,sep="\n",append=TRUE)
  cat("BDLvmsleaf = 16",file=file,sep="\n",append=TRUE)
  cat("BDLvmsstem = 25",file=file,sep="\n",append=TRUE)
  cat("BDLvmsroot = 35",file=file,sep="\n",append=TRUE)
  cat("BDAcroleaf = 16",file=file,sep="\n",append=TRUE)
  cat("BDAcrostem = 25",file=file,sep="\n",append=TRUE)
  cat("BDAcroroot = 35",file=file,sep="\n",append=TRUE)
  cat("BDCatoleaf = 25",file=file,sep="\n",append=TRUE)
  cat("BDCatostem = 30",file=file,sep="\n",append=TRUE)
  cat("BDCatoroot = 35",file=file,sep="\n",append=TRUE)
  cat("Beta = 0.7",file=file,sep="\n",append=TRUE)
  cat("CAllocFrleaf = 0.40",file=file,sep="\n",append=TRUE)
  cat("CAllocFrstem = 0.40",file=file,sep="\n",append=TRUE)
  cat("CAllocFrroot = 0.20",file=file,sep="\n",append=TRUE)
  cat("CropFc = 0.9",file=file,sep="\n",append=TRUE)
  cat("DecParLvmsleaf = 0.24",file=file,sep="\n",append=TRUE)
  cat("DecParLvmsstem = 0.24",file=file,sep="\n",append=TRUE)
  cat("DecParLvmsroot = 0.24",file=file,sep="\n",append=TRUE)
  cat("DecParAcroleaf = 0.13",file=file,sep="\n",append=TRUE)
  cat("DecParAcrostem = 0.13",file=file,sep="\n",append=TRUE)
  cat("DecParAcroroot = 0.13",file=file,sep="\n",append=TRUE)
  cat("DecParCatoleaf = 0.00004",file=file,sep="\n",append=TRUE)
  cat("DecParCatostem = 0.00004",file=file,sep="\n",append=TRUE)
  cat("DecParCatoroot = 0.039",file=file,sep="\n",append=TRUE)
  cat(paste("KExt = ",x[1],sep=""),sep="\n",file=file,append=TRUE)
  cat(paste("MaxGr = ",x[2],sep=""),file=file,sep="\n",append=TRUE)
  cat(paste("MortFrLvmsleaf = ",x[3],sep=""),file=file,sep="\n",append=TRUE)
  cat("MortFrLvmsstem = 0",file=file,sep="\n",append=TRUE)
  cat("MortFrLvmsroot = 0",file=file,sep="\n",append=TRUE)
  cat("MortFrAcroleaf = 0",file=file,sep="\n",append=TRUE)
  cat("MortFrAcrostem = 0.06",file=file,sep="\n",append=TRUE)
  cat("MortFrAcroroot = 0",file=file,sep="\n",append=TRUE)
  cat("MortFrCatoleaf = 0",file=file,sep="\n",append=TRUE)
  cat("MortFrCatostem = 0",file=file,sep="\n",append=TRUE)
  cat("MortFrCatoroot = 0.10",file=file,sep="\n",append=TRUE)
  cat("NAllocFrleaf = 0.45",file=file,sep="\n",append=TRUE)
  cat("NAllocFrstem = 0.40",file=file,sep="\n",append=TRUE)
  cat("NAllocFrroot = 0.15",file=file,sep="\n",append=TRUE)
  cat("NConcMax = 0.030",file=file,sep="\n",append=TRUE)
  cat("NconcMin = 0.020",file=file,sep="\n",append=TRUE)
  cat("ReallFrleaf = 0.45",file=file,sep="\n",append=TRUE)
  cat("ReallFrstem = 0.00",file=file,sep="\n",append=TRUE)
  cat("ReallFrroot = 0.30",file=file,sep="\n",append=TRUE)
  cat(paste("SLA = ",x[4],sep=""),file=file,sep="\n",append=TRUE)
  cat("TMaxGr = 25",file=file,sep="\n",append=TRUE)
  cat("TMinGr = 2",file=file,sep="\n",append=TRUE)
  cat("TOpt1Gr = 12",file=file,sep="\n",append=TRUE)
  cat("TOpt2Gr = 20",file=file,sep="\n",append=TRUE)
  cat("WLMax = 1000",file=file,sep="\n",append=TRUE)
  cat("WLMin = -100",file=file,sep="\n",append=TRUE)
  cat("WLOpt1 = 0",file=file,sep="\n",append=TRUE)
  cat("WLOpt2 = 400",file=file,sep="\n",append=TRUE)


  cat("",file=file,sep="\n",append=TRUE)


  cat("[eric]",file=file,sep="\n",append=TRUE)
  cat("BDLvmsleaf = 16",file=file,sep="\n",append=TRUE)
  cat("BDLvmsstem = 100",file=file,sep="\n",append=TRUE)
  cat("BDLvmsroot = 70",file=file,sep="\n",append=TRUE)
  cat("BDAcroleaf = 16",file=file,sep="\n",append=TRUE)
  cat("BDAcrostem = 100",file=file,sep="\n",append=TRUE)
  cat("BDAcroroot = 70",file=file,sep="\n",append=TRUE)
  cat("BDCatoleaf = 25",file=file,sep="\n",append=TRUE)
  cat("BDCatostem = 100",file=file,sep="\n",append=TRUE)
  cat("BDCatoroot = 70",file=file,sep="\n",append=TRUE)
  cat("Beta = 0.7",file=file,sep="\n",append=TRUE)
  cat("CAllocFrleaf = 0.35",file=file,sep="\n",append=TRUE)
  cat("CAllocFrstem = 0.30",file=file,sep="\n",append=TRUE)
  cat("CAllocFrroot = 0.35",file=file,sep="\n",append=TRUE)
  cat("CropFc = 0.7",file=file,sep="\n",append=TRUE)
  cat("DecParLvmsleaf = 0.17",file=file,sep="\n",append=TRUE)
  cat("DecParLvmsstem = 0.17",file=file,sep="\n",append=TRUE)
  cat("DecParLvmsroot = 0.17",file=file,sep="\n",append=TRUE)
  cat("DecParAcroleaf = 0.08",file=file,sep="\n",append=TRUE)
  cat("DecParAcrostem = 0.06",file=file,sep="\n",append=TRUE)
  cat("DecParAcroroot = 0.07",file=file,sep="\n",append=TRUE)
  cat("DecParCatoleaf = 0.00004",file=file,sep="\n",append=TRUE)
  cat("DecParCatostem = 0.00004",file=file,sep="\n",append=TRUE)
  cat("DecParCatoroot = 0.00004",file=file,sep="\n",append=TRUE)
  cat(paste("KExt = ",x[5],sep=""),file=file,sep="\n",append=TRUE)
  cat(paste("MaxGr = ",x[6],sep=""),file=file,sep="\n",append=TRUE)
  cat("MortFrLvmsleaf = 0.04",file=file,sep="\n",append=TRUE)
  cat("MortFrLvmsstem = 0",file=file,sep="\n",append=TRUE)
  cat("MortFrLvmsroot = 0",file=file,sep="\n",append=TRUE)
  cat("MortFrAcroleaf = 0",file=file,sep="\n",append=TRUE)
  cat("MortFrAcrostem = 0.01",file=file,sep="\n",append=TRUE)
  cat("MortFrAcroroot = 0.04",file=file,sep="\n",append=TRUE)
  cat("MortFrCatoleaf = 0",file=file,sep="\n",append=TRUE)
  cat("MortFrCatostem = 0",file=file,sep="\n",append=TRUE)
  cat("MortFrCatoroot = 0",file=file,sep="\n",append=TRUE)
  cat("NAllocFrleaf = 0.45",file=file,sep="\n",append=TRUE)
  cat("NAllocFrstem = 0.25",file=file,sep="\n",append=TRUE)
  cat("NAllocFrroot = 0.30",file=file,sep="\n",append=TRUE)
  cat("NConcMax = 0.022",file=file,sep="\n",append=TRUE)
  cat("NconcMin = 0.014",file=file,sep="\n",append=TRUE)
  cat("ReallFrleaf = 0.25",file=file,sep="\n",append=TRUE)
  cat("ReallFrstem = 0.00",file=file,sep="\n",append=TRUE)
  cat("ReallFrroot = 0.10",file=file,sep="\n",append=TRUE)
  cat(paste("SLA = ",x[7],sep=""),file=file,sep="\n",append=TRUE)
  cat("TMaxGr = 25",file=file,sep="\n",append=TRUE)
  cat("TMinGr = 5",file=file,sep="\n",append=TRUE)
  cat("TOpt1Gr = 14",file=file,sep="\n",append=TRUE)
  cat("TOpt2Gr = 20",file=file,sep="\n",append=TRUE)
  cat("WLMax = 600",file=file,sep="\n",append=TRUE)
  cat("WLMin = 50",file=file,sep="\n",append=TRUE)
  cat(paste("WLOpt1 = ",x[8],sep=""),file=file,sep="\n",append=TRUE)
  cat("WLOpt2 = 300",file=file,sep="\n",append=TRUE)

  cat("",file=file,sep="\n",append=TRUE)

  cat("[humm]",file=file,sep="\n",append=TRUE)
  cat("BDLvmsshoot = 9",file=file,sep="\n",append=TRUE)
  cat("BDAcroshoot = 20",file=file,sep="\n",append=TRUE)
  cat("BDCatoshoot = 40",file=file,sep="\n",append=TRUE)
  cat("Beta = 0.7",file=file,sep="\n",append=TRUE)
  cat(paste("CAllocFrshoot = ",x[9],sep=""),file=file,sep="\n",append=TRUE)
  cat("CropFc = 1.4",file=file,sep="\n",append=TRUE)
  cat("DecParLvmsshoot = 0.02",file=file,sep="\n",append=TRUE)
  cat("DecParAcroshoot = 0.02",file=file,sep="\n",append=TRUE)
  cat("DecParCatoshoot = 0.00004",file=file,sep="\n",append=TRUE)
  cat(paste("MaxGr = ",x[10],sep=""),file=file,sep="\n",append=TRUE)
  cat("MortFrLvmsshoot = 0",file=file,sep="\n",append=TRUE)
  cat(paste("MortFrAcroshoot = ",x[11],sep=""),file=file,sep="\n",append=TRUE)
  cat("MortFrCatoshoot = 0",file=file,sep="\n",append=TRUE)
  cat("NAllocFrshoot = 1",file=file,sep="\n",append=TRUE)
  cat("NConcMax = 0.032",file=file,sep="\n",append=TRUE)
  cat("NConcMin = 0.032",file=file,sep="\n",append=TRUE)
  cat("ReallFrshoot = 0.40",file=file,sep="\n",append=TRUE)
  cat(paste("TMaxGr = ",x[12],sep=""),file=file,sep="\n",append=TRUE)
  cat("TMinGr = 5",file=file,sep="\n",append=TRUE)
  cat(paste("TOpt1Gr = ",x[13],sep=""),file=file,sep="\n",append=TRUE)
  cat(paste("TOpt2Gr = ",x[14],sep=""),file=file,sep="\n",append=TRUE)
  cat("WLMax = 500",file=file,sep="\n",append=TRUE)
  cat("WLMin = 0",file=file,sep="\n",append=TRUE)
  cat("WLOpt1 = 50",file=file,sep="\n",append=TRUE)
  cat("WLOpt2 = 200",file=file,sep="\n",append=TRUE)

  cat("",file=file,sep="\n",append=TRUE)

  cat("[lawn]",file=file,sep="\n",append=TRUE)
  cat("BDLvmsshoot = 7",file=file,sep="\n",append=TRUE)
  cat("BDAcroshoot = 13",file=file,sep="\n",append=TRUE)
  cat("BDCatoshoot = 25",file=file,sep="\n",append=TRUE)
  cat("Beta = 0.7",file=file,sep="\n",append=TRUE)
  cat(paste("CAllocFrshoot = ",x[15],sep=""),file=file,sep="\n",append=TRUE)
  cat("CropFc = 1.3",file=file,sep="\n",append=TRUE)
  cat("DecParLvmsshoot = 0.04",file=file,sep="\n",append=TRUE)
  cat("DecParAcroshoot = 0.04",file=file,sep="\n",append=TRUE)
  cat("DecParCatoshoot = 0.00004",file=file,sep="\n",append=TRUE)
  cat(paste("MaxGr = ",x[16],sep=""),file=file,sep="\n",append=TRUE)
  cat("MortFrLvmsshoot = 0",file=file,sep="\n",append=TRUE)
  cat(paste("MortFrAcroshoot = ",x[17],sep=""),file=file,sep="\n",append=TRUE)
  cat("MortFrCatoshoot = 0",file=file,sep="\n",append=TRUE)
  cat("NAllocFrshoot = 1",file=file,sep="\n",append=TRUE)
  cat("NConcMax = 0.036",file=file,sep="\n",append=TRUE)
  cat("NconcMin = 0.006",file=file,sep="\n",append=TRUE)
  cat("ReallFrshoot = 0.40",file=file,sep="\n",append=TRUE)
  cat(paste("TMaxGr = ",x[18],sep=""),file=file,sep="\n",append=TRUE)
  cat("TMinGr = 3",file=file,sep="\n",append=TRUE)
  cat(paste("TOpt1Gr = ",x[19],sep=""),file=file,sep="\n",append=TRUE)
  cat(paste("TOpt2Gr = ",x[20],sep=""),file=file,sep="\n",append=TRUE)
  cat("WLMax = 350",file=file,sep="\n",append=TRUE)
  cat("WLMin = 0",file=file,sep="\n",append=TRUE)
  cat("WLOpt1 = 50",file=file,sep="\n",append=TRUE)
  cat("WLOpt2 = 150",file=file,sep="\n",append=TRUE)

  cat("",file=file,sep="\n",append=TRUE)

  cat("[holl]",file=file,sep="\n",append=TRUE)
  cat("BDLvmsshoot = 5",file=file,sep="\n",append=TRUE)
  cat("BDAcroshoot = 15",file=file,sep="\n",append=TRUE)
  cat("BDCatoshoot = 30",file=file,sep="\n",append=TRUE)
  cat("Beta = 0.7",file=file,sep="\n",append=TRUE)
  cat(paste("CAllocFrshoot = ",x[21],sep=""),file=file,sep="\n",append=TRUE)
  cat("CropFc = 1.2",file=file,sep="\n",append=TRUE)
  cat("DecParLvmsshoot = 0.08",file=file,sep="\n",append=TRUE)
  cat("DecParAcroshoot = 0.08",file=file,sep="\n",append=TRUE)
  cat("DecParCatoshoot = 0.00004",file=file,sep="\n",append=TRUE)
  cat(paste("MaxGr = ",x[22],sep=""),file=file,sep="\n",append=TRUE)
  cat("MortFrLvmsshoot = 0",file=file,sep="\n",append=TRUE)
  cat(paste("MortFrAcroshoot = ",x[23],sep=""),file=file,sep="\n",append=TRUE)
  cat("MortFrCatoshoot = 0",file=file,sep="\n",append=TRUE)
  cat("NAllocFrshoot = 1",file=file,sep="\n",append=TRUE)
  cat("NConcMax = 0.042",file=file,sep="\n",append=TRUE)
  cat("NconcMin = 0.008",file=file,sep="\n",append=TRUE)
  cat("ReallFrshoot = 0.40",file=file,sep="\n",append=TRUE)
  cat(paste("TMaxGr = ",x[24],sep=""),file=file,sep="\n",append=TRUE)
  cat("TMinGr = 0",file=file,sep="\n",append=TRUE)
  cat(paste("TOpt1Gr = ",x[25],sep=""),file=file,sep="\n",append=TRUE)
  cat(paste("TOpt2Gr = ",x[26],sep=""),file=file,sep="\n",append=TRUE)
  cat("WLMax = 200",file=file,sep="\n",append=TRUE)
  cat("WLMin = -100",file=file,sep="\n",append=TRUE)
  cat("WLOpt1 = 0",file=file,sep="\n",append=TRUE)
  cat("WLOpt2 = 50",file=file,sep="\n",append=TRUE)
}
